version: "3"
services:
  ngnix: 
    ports:
      - "80:80"
  node-docker-app:
    build: 
      context: .
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node server.js