version: "3"
services:
  node-docker-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=pradeep
      - MONGO_PASSWORD=pradeep19
      - MONGO_DB_NAME=node_docker
    command: npm run dev
  
  mongodb: 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pradeep
      - MONGO_INITDB_ROOT_PASSWORD=pradeep19