version: "3"
services:
  node-docker-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongodb
      - redisdb
    # env_file: 
    #   - ./.env

  mongodb: 
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pradeep
      - MONGO_INITDB_ROOT_PASSWORD=pradeep19
    volumes:
      - mongo-db:/data/db

  redisdb: 
    image: redis
    

volumes:
  mongo-db: